package com.Aakash.pojos;

// Generated Aug 17, 2015 2:47:43 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name = "questions", catalog = "crossover", uniqueConstraints = @UniqueConstraint(columnNames = "order"))
public class Questions implements java.io.Serializable {

	private Integer id;
	private String title;
	private String description;
	private Boolean multipleCorrectChoice;
	private int order;

	public Questions() {
	}

	public Questions(int order) {
		this.order = order;
	}

	public Questions(String title, String description,
			Boolean multipleCorrectChoice, int order) {
		this.title = title;
		this.description = description;
		this.multipleCorrectChoice = multipleCorrectChoice;
		this.order = order;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Title", length = 45)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "multiple_correct_choice")
	public Boolean getMultipleCorrectChoice() {
		return this.multipleCorrectChoice;
	}

	public void setMultipleCorrectChoice(Boolean multipleCorrectChoice) {
		this.multipleCorrectChoice = multipleCorrectChoice;
	}

	@Column(name = "order", unique = true, nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

}
